# Generated by Django 3.0.4 on 2020-05-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Census',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUMLEV', models.IntegerField()),
                ('STATE', models.IntegerField()),
                ('COUNTY', models.IntegerField()),
                ('PLACE', models.IntegerField()),
                ('COUSUB', models.IntegerField()),
                ('CONCIT', models.IntegerField()),
                ('FUNCSTAT', models.CharField(max_length=100)),
                ('NAME', models.CharField(max_length=100)),
                ('STNAME', models.CharField(max_length=100)),
                ('CENSUS2010POP', models.IntegerField()),
                ('ESTIMATESBASE2010', models.IntegerField()),
                ('POPESTIMATE2010', models.IntegerField()),
                ('POPESTIMATE2011', models.IntegerField()),
                ('POPESTIMATE2012', models.IntegerField()),
                ('POPESTIMATE2013', models.IntegerField()),
                ('POPESTIMATE2014', models.IntegerField()),
                ('POPESTIMATE2015', models.IntegerField()),
                ('POPESTIMATE2016', models.IntegerField()),
                ('POPESTIMATE2017', models.IntegerField()),
                ('POPESTIMATE2018', models.IntegerField()),
                ('POPESTIMATE2019', models.IntegerField()),
            ],
        ),
    ]
