# Generated by Django 3.0.4 on 2020-05-23 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='census',
            old_name='consub',
            new_name='cousub',
        ),
    ]
