# Generated by Django 3.0.4 on 2020-05-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='census',
            old_name='CENSUS2010POP',
            new_name='census2010pop',
        ),
        migrations.RenameField(
            model_name='census',
            old_name='CONCIT',
            new_name='concit',
        ),
        migrations.RenameField(
            model_name='census',
            old_name='COUNTY',
            new_name='consub',
        ),
        migrations.RenameField(
            model_name='census',
            old_name='COUSUB',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='census',
            old_name='ESTIMATESBASE2010',
            new_name='estimatebase2010',
        ),
        migrations.RenameField(
            model_name='census',
            old_name='FUNCSTAT',
            new_name='funcstat',
        ),
        migrations.RenameField(
            model_name='census',
            old_name='NAME',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='census',
            old_name='PLACE',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='census',
            old_name='POPESTIMATE2010',
            new_name='popestimate2010',
        ),
        migrations.RenameField(
            model_name='census',
            old_name='POPESTIMATE2011',
            new_name='popestimate2011',
        ),
        migrations.RenameField(
            model_name='census',
            old_name='POPESTIMATE2012',
            new_name='popestimate2012',
        ),
        migrations.RenameField(
            model_name='census',
            old_name='POPESTIMATE2013',
            new_name='popestimate2013',
        ),
        migrations.RenameField(
            model_name='census',
            old_name='POPESTIMATE2014',
            new_name='popestimate2014',
        ),
        migrations.RenameField(
            model_name='census',
            old_name='POPESTIMATE2015',
            new_name='popestimate2015',
        ),
        migrations.RenameField(
            model_name='census',
            old_name='POPESTIMATE2016',
            new_name='popestimate2016',
        ),
        migrations.RenameField(
            model_name='census',
            old_name='POPESTIMATE2017',
            new_name='popestimate2017',
        ),
        migrations.RenameField(
            model_name='census',
            old_name='POPESTIMATE2018',
            new_name='popestimate2018',
        ),
        migrations.RenameField(
            model_name='census',
            old_name='POPESTIMATE2019',
            new_name='popestimate2019',
        ),
        migrations.RenameField(
            model_name='census',
            old_name='STATE',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='census',
            old_name='STNAME',
            new_name='stname',
        ),
        migrations.RenameField(
            model_name='census',
            old_name='SUMLEV',
            new_name='sumlev',
        ),
    ]
