# Generated by Django 3.0.4 on 2020-05-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0003_census_primgeo_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='census2010pop',
            field=models.CharField(max_length=100),
        ),
    ]
