# Generated by Django 3.0.4 on 2020-05-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0004_auto_20200523_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumlev', models.IntegerField()),
                ('region', models.IntegerField()),
                ('division', models.IntegerField()),
                ('state', models.IntegerField()),
                ('county', models.IntegerField()),
                ('stname', models.CharField(max_length=100)),
                ('ctyname', models.CharField(max_length=100)),
                ('census2010pop', models.IntegerField()),
                ('estimatesbase2010', models.IntegerField()),
                ('popestimate2010', models.IntegerField()),
                ('popestimate2011', models.IntegerField()),
                ('popestimate2012', models.IntegerField()),
                ('popestimate2013', models.IntegerField()),
                ('popestimate2014', models.IntegerField()),
                ('popestimate2015', models.IntegerField()),
                ('popestimate2016', models.IntegerField()),
                ('popestimate2017', models.IntegerField()),
                ('popestimate2018', models.IntegerField()),
                ('popestimate2019', models.IntegerField()),
            ],
        ),
    ]
